services:
  stellarium:
    build: .
    image: sirius-stellarium
    container_name: sirius-stellarium
    expose:
      - "8000"
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
